/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLoadingSpinner: typeof import('element-plus/es')['ElLoadingSpinner']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PaymentModal: typeof import('./src/components/PaymentModal.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    RegisterModal: typeof import('./src/components/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
